#!/usr/bin/python
import sys


fd = open( sys.argv[1], "r" )
state = 0
for line in fd:
   line = line.rstrip()
   if state == 0:
      if line.startswith("static size_t GetObjSize( AstObject") and line.endswith("{"):
         state = 1
         nname = 0
   elif state == 1:
      if line.startswith("   int result;"):
         line = line.replace("   int result;   ","   size_t result;",1)
         line = line.replace("   int result;","   size_t result;",1)
         state = 3
      elif line.startswith("*  Name:"):
         nname += 1
         if nname == 2:
            state = 2
   print(line)

fd.close()
